#!/usr/bin/env bash

set -eu

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
readonly ATERM="java -jar $DIR/../bin/org.metaborg.sunshine2-2.5.2.jar parse -l $DIR/../lib/java.spfx/lang.java -p . -i"

for infile in "$@"
do
	javac ${infile} 2>&1 | tee ${infile%.java}.javac.out 
	java_ok=${PIPESTATUS[0]}

	jav=${infile%.java}.jav
	cp ${infile} $jav
	${ATERM} ${infile%.java}.jav > ${infile%.java}.aterm 2> /dev/null
	statix $DIR/../src/java.mstx ${infile%.java}.aterm 2>&1 | tee ${infile%.java}.stx.out
	stx_ok=${PIPESTATUS[0]}

	if [ $java_ok -eq $stx_ok ]
	then
		echo -e "[\e[32mSUCCESS\e[0m] $infile"
	else
		echo -e "[\e[31mFAILURE\e[0m] $infile"
	fi
done
