#!/usr/bin/env bash

set -eu

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

readonly JAVADIR="$DIR/../lib/java.spfx/lang.java"
if [ ! -d "$JAVADIR" ]; then
    echo "FAILURE: Cannot find directory $JAVADIR"
    exit 1
fi

readonly SUNSHINE_JAR="$DIR/../bin/org.metaborg.sunshine2-2.6.0-SNAPSHOT.jar"
if [ ! -f "$SUNSHINE_JAR" ]; then
    echo "FAILURE: Cannot find file $SUNSHINE_JAR"
    exit 1
fi

readonly SUNSHINE="java -jar $SUNSHINE_JAR"

statix check -I $DIR/../src/ java 2>&1
stx_runs=${PIPESTATUS[0]}
if [ ! $stx_runs ]; then
    echo "FAILURE: Cannot run statix"
    exit 1
fi

if true || test -t 1; then
   SUCCESS="[\e[32mSUCCESS\e[0m]"
   FAILURE="[\e[31mFAILURE\e[0m]"
   STUCK="[\e[34mSTUCK\e[0m]"
else
    SUCCESS="[SUCCESS]"
    FAILURE="[FAILURE]"
    STUCK="[STUCK]"
fi

function agree {
    [ $1 -eq 0 -a $2 -eq 0 ] || [ $1 -ne 0 -a $2 -ne 0 ]
}

for infile in "$@"
do
    if ! (echo $infile | grep -s "no.java") 
    then
        positive=0
	echo "Expect pass"
    else
        positive=1
	echo "Expect fail"
    fi

    # make sure to remove all class files to avoid incidental capture
    rm -f $(dirname "$infile")/*.class

    # run java compiler
    javac $infile 2>&1 | tee ${infile%.java}.javac.out 
    java_ok=${PIPESTATUS[0]}

    # compile the file to an aterm
    jav=${infile%.java}.jav
    cp "$infile" $jav
    ${SUNSHINE} transform -n "Explicate injections" -l "${JAVADIR}" -p . -i ${infile%.java}.jav > ${infile%.java}.aterm 2> /dev/null

    # run statix on the aterm
    statix check -I $DIR/../src/ java ${infile%.java}.aterm 2>&1 | tee ${infile%.java}.stx.out
    stx_ok=${PIPESTATUS[0]}

    # compute test result by comparison
    if [ $stx_ok -eq 65 ]; then
        echo -e "$STUCK $infile"
    elif agree $stx_ok $java_ok && agree $java_ok $positive; then
        echo -e "$SUCCESS $infile"
    else
        echo -e "$FAILURE $infile"
    fi
done
